### ISSUE TITLE
Error in the GetUsageInfo method 

### ISSUE THREAD

**Issue by DACTYLE** [orbeus/Rekognition_API_PHP_SDK#3]
May you replace these lines in the GetUsageInfo method :

if(isset($this->account_info_[$key])) {
      $val = $this->account_info_[$key];
      return true;
}

by

if(isset($this->usage_info_[$key])) {
      $val = $this->usage_info_[$key];
      return true;
    }

**Comment by tqliu1122** [comment]
Just fixed it: 3032cbd57d883daaf1f5e5ca2767c83f3f4820bf, Thanks!
